Typos and misspellings in synset examples
globalwordnet/english-wordnet pull request #1017
Opened 2024-06-03 12:54 UTC by 1313ou

After applying a deep correction-model (ai-forever/sage) to raise suspicious cases (including punctuation, unknown terms, archaic words, ...), I reviewed the long list (about 10%) and hand-corrected to a short list of unambiguous cases (this PR).

I chose  a deep model to handle such cases as "The glass was opacified more greater privacy" where a word-by-word spellchecker fails to see the issue arising from assembling individually valid words.

This deals with examples only, to the exclusion of definitions. Punctuation, capitalization and other issues (like the use of the infamous '--') have been left aside for now. Hopefully these will also be handled at a later stage.

The 'hand' review and correction mean some misspellings may have sneaked through. Inversely I may have introduced false positives. So external reviewing is required.

2024-06-04 08:37 UTC, jmccrae requested changes

2024-06-04 08:37 UTC, jmccrae commented on src/yaml/adj.all.yaml
> +  - (`ambagious' is archaic)
The source should be "T.S.Eliot"... the text "(`ambagious' is arachaic)" should probably be removed

2024-06-04 08:37 UTC, jmccrae commented on src/yaml/entries-b.yaml
> +Bleu Végétal Pour Les Veines:
In this case, we generally add an entry for both with and without accents

2024-06-04 08:37 UTC, jmccrae commented on src/yaml/noun.communication.yaml
> +    English has forms like eˈlongate, imˈpregnate and reˈmonstrate where British English
I don't think this is correct. Original source is here:
https://books.google.ie/books?id=0NOidwn8Mf0C&pg=PA202&lpg=PA202&dq=%22The+fronting+took+place+more+slowly+in+American+English+and+so+Modern+American%22&source=bl&ots=vm70LX5UJJ&sig=ACfU3U0xkns5-6hBFGUZvzwbIeVSCqQoHg&hl=en&sa=X&ved=2ahUKEwiR-5rGxcGGAxVraEEAHZFnEqkQ6AF6BAgJEAM#v=onepage&q=%22The%20fronting%20took%20place%20more%20slowly%20in%20American%20English%20and%20so%20Modern%20American%22&f=false

2024-06-04 09:48 UTC, 1313ou commented on src/yaml/noun.communication.yaml
> +    English has forms like eˈlongate, imˈpregnate and reˈmonstrate where British English
Link is dead for me. As I understand it the example was to mean that elongate, impregnate, remonstrate have stress on the 2nd syllable in US English, first in British English. IPA uses accents BEFORE the stressed syllable. 'imprégnate', à-la-French, is clearly unacceptable. What do you suggest ?

2024-06-04 09:50 UTC, 1313ou commented on src/yaml/entries-b.yaml
> +Bleu Végétal Pour Les Veines:
What was unacceptable was the hybrid 'Végetal'. Either both 'e's are accented or none. While I was at it I thought it better to correct it the French way.

2024-06-04 09:54 UTC, 1313ou commented on src/yaml/adj.all.yaml
> +  - (`ambagious' is archaic)
I agree. I thought, the "(`ambagious' is archaic)" part should be preserved as a usage note (more than an example) but is has nothing to do the TS Eliot's quotation. So I moved it out. What is the usage attribute to put it in?-

2024-06-04 11:55 UTC, jmccrae commented on src/yaml/adj.all.yaml
> +  - (`ambagious' is archaic)
The best fix would be to add the link `exemplifies archaism%1:10:00::`.

2024-06-04 11:57 UTC, jmccrae commented on src/yaml/noun.communication.yaml
> +    English has forms like eˈlongate, imˈpregnate and reˈmonstrate where British English
I would suggest the following
```yaml
text: The fronting took place more slowly in American English and so Modern American
    English has forms like elóngate, imprégnate and remónstrate where British English
    usually has initial stress.
source: English Phonetics and Phonology for Spanish Students - Brian Mott
```

2024-06-04 19:14 UTC, 1313ou commented
[See Merriam Webster on how to use dashes](https://www.merriam-webster.com/grammar/em-dash-en-dash-how-to-use)

2024-06-05 11:03 UTC, jmccrae approved these changes

2024-06-05 11:03 UTC, merged